version: "3"

services:
  Router:
    image: seed-ubuntu-base-image
    container_name: router-11
    tty: true
    sysctls:
      - net.ipv4.ip_forward=1
    networks:
      net-10.9.0.0:
        ipv4_address: 10.9.0.11
      net-192.168.60.0:
        ipv4_address: 192.168.60.11
    command: bash -c "
      ip route del default  &&
      ip route add default via 10.9.0.1 &&
      /start.sh
      "
  HostA:
    build: ./ubuntu_base
    image: seed-ubuntu-base-image
    container_name: attacker-10.9.0.5
    tty: true
    cap_add:
      - ALL
    networks:
      net-10.9.0.0:
        ipv4_address: 10.9.0.5
    command: bash -c "
      ip route add 192.168.60.0/24 via 10.9.0.11 &&
      /start.sh
      "

  HostB:
    image: seed-ubuntu-base-image
    container_name: server-10.9.0.6
    tty: true
    cap_add:
      - ALL
    networks:
      net-10.9.0.0:
        ipv4_address: 10.9.0.6
    command: bash -c "
      ip route del default  &&
      ip route add default via 192.168.60.11  &&
      /start.sh
      "

  HostC:
    image: seed-ubuntu-base-image
    container_name: neutral-10.9.0.7
    tty: true
    cap_add:
      - ALL
    networks:
      net-10.9.0.0:
        ipv4_address: 10.9.0.7
    command: bash -c "
      ip route del default  &&
      ip route add default via 192.168.60.12  &&
      /start.sh
      "

networks:
  net-10.9.0.0:
    name: net-10.9.0.0
    ipam:
      config:
        - subnet: 10.9.0.0/24

  net-192.168.60.0:
    name: net-192.168.60.0
    ipam:
      config:
        - subnet: 192.168.60.0/24
